{"glass": "0.42%", "top_result": "paper", "cardboard": "0.06%", "metal": "0.0%", "paper": "97.78%", "plastic": "0.98%", "others": "0.77%"}
172.31.39.61
 * Serving Flask app "flask_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
35.193.231.210 - - [16/Nov/2019 06:45:29] "POST /classifier HTTP/1.1" 200 -
35.193.231.210 - - [16/Nov/2019 06:45:33] "POST /classifier HTTP/1.1" 200 -
35.193.231.210 - - [16/Nov/2019 06:46:25] "POST /classifier HTTP/1.1" 200 -
35.193.231.210 - - [16/Nov/2019 06:50:17] "POST /classifier HTTP/1.1" 200 -
35.193.231.210 - - [16/Nov/2019 06:53:20] "POST /classifier HTTP/1.1" 200 -
35.193.231.210 - - [16/Nov/2019 06:54:48] "POST /classifier HTTP/1.1" 200 -
35.193.231.210 - - [16/Nov/2019 07:03:05] "POST /classifier HTTP/1.1" 200 -
[2019-11-16 08:35:25,734] ERROR in app: Exception on /classifier [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "flask_server.py", line 113, in classifier
    base64_in=request.json["in_base64_string"]
TypeError: 'NoneType' object is not subscriptable
37.201.225.229 - - [16/Nov/2019 08:35:25] "GET /classifier HTTP/1.1" 500 -
37.201.225.229 - - [16/Nov/2019 08:35:26] "GET /favicon.ico HTTP/1.1" 404 -
[2019-11-16 09:33:15,604] ERROR in app: Exception on /classifier [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "flask_server.py", line 113, in classifier
    base64_in=request.json["in_base64_string"]
TypeError: 'NoneType' object is not subscriptable
193.175.49.143 - - [16/Nov/2019 09:33:15] "GET /classifier HTTP/1.1" 500 -
193.175.49.143 - - [16/Nov/2019 09:33:16] "GET /favicon.ico HTTP/1.1" 404 -
{"metal": "0.0%", "cardboard": "0.06%", "top_result": "paper", "plastic": "0.98%", "glass": "0.42%", "others": "0.77%", "paper": "97.78%"}
172.31.39.61
 * Serving Flask app "flask_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
3.209.31.93 - - [16/Nov/2019 09:35:10] "[37mPOST /classifier HTTP/1.1[0m" 200 -
